### PR TITLE
Added BS4

### LINKED ISSUE #24: Integrate bootstrap CSS in this project.
Instructions:

1.  Create a separate folder with the name ```css``` in the root directory.
2. Download all bootstrap CSS files from the official website.
3. Add bootstrap in the index.html file.

### PR DESCRIPTION
**Pull request by sarthakm21**
__24__ 

Fixes #24

#### Short description of what this resolves:
Added bootstrap 4 into the source folder

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by thesmallstar** [comment]
Live link?

**Comment by thesmallstar** [comment]
It was expected you also add some bootstrap classes.

**Comment by sarthakm21** [comment]
@thesmallstar 
Does this look better??
rank

**Comment by abhishekmsingh** [comment]
live link?

**Comment by sarthakm21** [comment]
https://sarthakm21.github.io/

**Comment by sarthakm21** [comment]
I have a 2nd alternative too if it looks better
rank_dark

**Comment by sarthakm21** [comment]
@thesmallstar @abhiandthetruth should I continue??

**Comment by thesmallstar** [comment]
@sarthakm21  did you check the mobile view?
You need to fix that :)

**Pull request closed without merging**
