### PR TITLE
Leaderboard Logo

### LINKED ISSUE #50: Redesign leaderboard header/logo
For both search and main page.

### PR DESCRIPTION
**Pull request by Rohini13**
__50__ 
https://rohini13.github.io/Opencode-20-LeaderBoard-Frontend/index.html

Fixes #50 

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by thesmallstar** [comment]
Check mobile view, also search page logo is not added.

**Comment by zerefwayne** [comment]
@Rohini13 Do the changes as suggested by @thesmallstar.

**Comment by Rohini13** [comment]
Added search page logo, checked mobile view.
https://rohini13.github.io/Opencode-20-LeaderBoard-Frontend/
Screenshot (46)
Screenshot (45)

**Comment by thesmallstar** [comment]
Please solve conflicts

**Comment by Rohini13** [comment]
@thesmallstar resolved conflicts

**Pull request merged**
