### PR TITLE
Added bootstrap and some components

### LINKED ISSUE #24: Integrate bootstrap CSS in this project.
Instructions:

1.  Create a separate folder with the name ```css``` in the root directory.
2. Download all bootstrap CSS files from the official website.
3. Add bootstrap in the index.html file.

### PR DESCRIPTION
**Pull request by sarthakm21**
__24__ 

Fixes #24

#### Short description of what this resolves:
Added BS4 and its components
Also, fixed the website for mobile viewing

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by thesmallstar** [comment]
good :)

**Comment by thesmallstar** [comment]
@sarthakm21 did I miss anything? I don't see it responsive on the live link.
can you fix it?

**Comment by sarthakm21** [comment]
@thesmallstar But sir, it is working well for all screen sizes......
lb

**Comment by sarthakm21** [comment]
Okay, I see the issue. Working on it.

**Pull request merged**
