### PR TITLE
Displayed top 3 in leaderboard as bold

### LINKED ISSUE #12: Display top 3 in leaderboard as bold

### PR DESCRIPTION
**Pull request by untrulynoxiusmj**
__12__ 

Fixes #12

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by thesmallstar** [comment]
can you give a live link?

**Comment by thesmallstar** [comment]
can you give a live link? and please fill the issue template properly.
use this if required: https://guides.github.com/features/pages/

**Comment by untrulynoxiusmj** [comment]
12

Fixes #12

Short description of what this resolves:
Displays Top 3 in leader board as bold

Changes proposed in this pull request and/or Screenshots of changes:
Before:
before
After:
Capture

**Comment by untrulynoxiusmj** [comment]
ok sir ! i will provide a live link

**Comment by untrulynoxiusmj** [comment]
live link
https://untrulynoxiusmj.github.io/pages/index.html

**Review by thesmallstar — APPROVED** [review]

**Pull request merged**
