### PR TITLE
Added Participant Photo

### LINKED ISSUE #9: Add Particiapnt photo in table
the get request also has participant logo URL,  add participant image before name

### PR DESCRIPTION
**Pull request by JLodha**
__9__

Fixes #9 

#### Short description of what this resolves:
As per the issue i added photo of each participant present in the leaderboard

#### Changes proposed in this pull request and/or Screenshots of changes:

- Added a new column in the leader board for the image of the participant
- Modified the index.html file for the same.
- Screenshot :

Screenshot_1

### CODE REVIEW

**Comment by thesmallstar** [comment]
live link?

**Comment by JLodha** [comment]
Sir live link is not working properly.
I have added the screenshot. Please check it out
Thank you
> live link?

**Comment by thesmallstar** [comment]
Update your repo, we have changed quite a many changes, nothing is visible here.

**Comment by JLodha** [comment]
Okay sir please give me some time
Thanks

**Pull request closed without merging**
