### PR TITLE
Added leaderboard logo

### LINKED ISSUE #11: Add a Header logo for opencode'20 leaderboard

### PR DESCRIPTION
**Pull request by padityak79**
__11__ 

Fixes #11

#### Changes proposed in this pull request and/or Screenshots of changes:

-before change:
image

-after change:
image

-

### CODE REVIEW

**Comment by thesmallstar** [comment]
Hey
can you keep the logo a big (maybe opencode logo itself with minor change) simple and properly sized?

**Comment by padityak79** [comment]
ok sir.

**Comment by padityak79** [comment]
Sir, I updated the logo. Please have a look at it.
after change-
image

**Comment by thesmallstar** [comment]
Can you also mention leaderboard in the logo?  
this looks great though.

**Comment by padityak79** [comment]
Added leaderboard in Logo.
After change-
image

**Comment by thesmallstar** [comment]
Great!

**Pull request merged**
