### PR TITLE
shows rank and points for each issue on search

### LINKED ISSUE #37: Show rank and points for each issue on search(Search page)

### PR DESCRIPTION
**Pull request by untrulynoxiusmj**
__37__ 

Fixes #37

#### Short description of what this resolves:

shows rank and points for each issue on search

#### Changes proposed in this pull request and/or Screenshots of changes:

rank

### CODE REVIEW

**Comment by thesmallstar** [comment]
Squash the commits.

**Comment by untrulynoxiusmj** [comment]
Sir, can u explain how to do that
hb

**Comment by thesmallstar** [comment]
pick a
pick b
pick c
s      D

if this is the scene. 
and you rebase, all the changes from a b and c would squash into D

**Comment by untrulynoxiusmj** [comment]
Sir please check now

**Comment by untrulynoxiusmj** [comment]
I have squashed the commits

**Comment by untrulynoxiusmj** [comment]
https://untrulynoxiusmj.github.io/Opencode-20-LeaderBoard-Frontend/search.html

**Comment by thesmallstar** [comment]
Nice :)

**Pull request merged**
