### PR TITLE
Added nav bar with home and seach button

### LINKED ISSUE #29: Add a nav bar with home and search button

### PR DESCRIPTION
**Pull request by untrulynoxiusmj**
__29__ 

Fixes #29

#### Short description of what this resolves:

Added nav bar with home and seach button

#### Changes proposed in this pull request and/or Screenshots of changes:

navbar

### CODE REVIEW

**Comment by untrulynoxiusmj** [comment]
> **29**
> 
> Fixes #29
> 
> #### Short description of what this resolves:
> Added nav bar with home and seach button
> 
> #### Changes proposed in this pull request and/or Screenshots of changes:
> navbar

live link :
https://untrulynoxiusmj.github.io/Opencode-20-LeaderBoard-Frontend/

**Comment by thesmallstar** [comment]
This can look better, what about icons and not buttons with some beautiful background?

**Comment by untrulynoxiusmj** [comment]
ok sir

**Comment by untrulynoxiusmj** [comment]
navbaricon

**Comment by thesmallstar** [comment]
Good :D 
Just can you add a link to the home button? 
using the <a tag?
try that the link should not break if URL changes

**Comment by thesmallstar** [comment]
Two things:
1. The <a link you have added is very specific, do something that it works for all repos/url
it doesn't work your live link either.
2. why did you add a bootstrap.css when it is already included?

**Comment by untrulynoxiusmj** [comment]
i didn't add bootstrap.css . I wrote styling for navbar in bootstrap.css

**Comment by untrulynoxiusmj** [comment]
link:
https://untrulynoxiusmj.github.io/Opencode-20-LeaderBoard-Frontend/index.html

**Comment by thesmallstar** [comment]
nice :)

**Pull request merged**
