### PR TITLE
Aligned all data to center

### LINKED ISSUE #6: Change Alignment of all data to center

### PR DESCRIPTION
**Pull request by JLodha**
__6__ 

Fixes #6 

#### Short description of what this resolves:
This PR does not resolves anything

#### Changes proposed in this pull request and/or Screenshots of changes:

-Uses the <center> </center> command to align every data to center of the page.
- Sorted all the data to center
-

### CODE REVIEW

**Comment by thesmallstar** [comment]
Can you give a live link?

**Comment by thesmallstar** [comment]
https://guides.github.com/features/pages/ use this if needed,

**Comment by JLodha** [comment]
Sir will screenshot do the work?

**Comment by JLodha** [comment]
Here is the link https://jlodha.github.io/Opencode-20-LeaderBoard-Frontend/

**Comment by abhishekmsingh** [comment]
Please align the rank-list to.

**Comment by thesmallstar** [comment]
@JLodha  You do not need to close the PR, just push more commits to the same branch. and It will automatically come in the PR

**Comment by JLodha** [comment]
Sir done the changes please have a look
Thanks

**Comment by thesmallstar** [comment]
@JLodha  solve  merge conflicts please.
Perform git pull upstream master 
and set upstream if required. google it if you get error

**Pull request closed without merging**
