### PR TITLE
Made responsive

### LINKED ISSUE #27: Make the website responsive

### PR DESCRIPTION
**Pull request by sarthakm21**
__27__ 

Fixes #27 

#### Short description of what this resolves:
The website is now working well on mobile too. Sorry for the previous errors.....

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by sarthakm21** [comment]
sarthakm21.github.io
Live link

**Comment by thesmallstar** [comment]
I like the old view. 
let other's try once.

**Comment by sarthakm21** [comment]
Okay.

**Comment by sarthakm21** [comment]
But if you want, I can make the changes to the previous version too...

**Pull request closed without merging**
