### PR TITLE
Make leaderboard responsive for all screen sizes

### LINKED ISSUE #64: Make leaderboard responsive for all screen sizes
379A58FF-835B-4A08-9980-61A1FF5DB329

There should not be bugs like this

### PR DESCRIPTION
**Pull request by sggts04**
__64__ 

Fixes #64

#### Short description of what this resolves:
Makes leaderboard responsive for all screen sizes

#### Changes proposed in this pull request and/or Screenshots of changes:
Live Link: https://shreyasgupta.in/Opencode-20-LeaderBoard-Frontend/

### CODE REVIEW

**Comment by thesmallstar** [comment]
@niftyy  had a issue on his phone,he need to verify this

**Comment by tushparte** [comment]
@sggts04 can you create a live link

**Comment by sggts04** [comment]
@niftyy https://shreyasgupta.in/Opencode-20-LeaderBoard-Frontend/

**Comment by tushparte** [comment]
D0BF4CA8-6E2C-4AA5-A9EC-26C91C20AE62
not fixed

**Comment by sggts04** [comment]
@niftyy this is a safari problem I believe. I can't emulate that to fix it

**Comment by sggts04** [comment]
@niftyy I feel this is a safari problem, I can't test that to fix it

**Comment by tushparte** [comment]
56736156-29CF-44E8-89C1-4457596FB642
firefox

**Comment by thesmallstar** [comment]
You can find some website that will give you the safari view. Also, use Chrome developers tools, might help for getting the apple phone size view.

**Comment by sggts04** [comment]
I am not able to recreate this, I tried Chrome Device Simulator
image
I tried Firefox Device Simulator
image
even tried sites like responsinator.com
image

**Comment by thesmallstar** [comment]
@niftyy

**Pull request merged**
