### PR TITLE
fixed issue no.4

### PR DESCRIPTION
**Pull request by blaze-assault**
__ISSUENUMBER__ 

Fixes #ISSUENUMBER

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by thesmallstar** [comment]
@blaze-assault 
2 Mistakes:
1. PR template is not to be edited, when you make a Pr you will get it in the editor. 
Write issue number there.
2. JS files should always be added above the end body tag. so as to speed up loading.

**Comment by blaze-assault** [comment]
Sir is it merged ?? As i cloned it agains to ractify my mistakes but  the
file was changed file was already there .

**Comment by thesmallstar** [comment]
You probably cloned from your own repo.  where you pushed the changes that's why.

**Comment by thesmallstar** [comment]
@blaze-assault  just bring the main.js file down, keep others above. 
Jquery and other js files have to be loaded first. since other JS files are dependant on them.

Perform 
git pull upstream master
before making more changes
if you get no upstream set the main/original repo as upstream.

**Pull request closed without merging**
