### PR TITLE
Added details icon which takes you to details of user on search page

### LINKED ISSUE #54: Clicking on user points in  home page takes you to detailed description of user displyed in search page

### PR DESCRIPTION
**Pull request by untrulynoxiusmj**
__54__ 

Fixes #54 

#### Short description of what this resolves:

Added details icon which takes you to details of user on search page

#### Changes proposed in this pull request and/or Screenshots of changes:

details

### CODE REVIEW

**Comment by untrulynoxiusmj** [comment]
live link  :
https://untrulynoxiusmj.github.io/test/

**Comment by thesmallstar** [comment]
Please solve conflicts

**Comment by untrulynoxiusmj** [comment]
live link :
https://untrulynoxiusmj.github.io/test/index.html

**Comment by thesmallstar** [comment]
Conflicts still, in  search.html

**Comment by thesmallstar** [comment]
From next time, commits should be squashed.

**Comment by untrulynoxiusmj** [comment]
live link :
https://untrulynoxiusmj.github.io/test/index.html

**Comment by zerefwayne** [comment]
@untrulynoxiusmj Clicking on the details icon takes me to the search page but user's details are not being displayed.

**Comment by untrulynoxiusmj** [comment]
https://drive.google.com/open?id=1EQU3AabqoiWsFv-Ag-D9m6-I42bkv1Lo

**Comment by untrulynoxiusmj** [comment]
Sir, they are being displayed. please watch this viseo

**Comment by thesmallstar** [comment]
@untrulynoxiusmj  
image Mobile view?

**Comment by untrulynoxiusmj** [comment]
https://drive.google.com/open?id=1z2rQnZeVVyQ2DiPzrW8EzeuUjd_4udoE

**Comment by untrulynoxiusmj** [comment]
Sir, is it fine

**Comment by untrulynoxiusmj** [comment]
mobile

**Comment by thesmallstar** [comment]
Great work!

**Pull request merged**
